### ISSUE TITLE
Function implementation progress

### ISSUE THREAD

**Issue by Zaid-Ajaj** [pulumi/pulumi-std#1]
### Numeric functions:
 - [x] [abs](https://developer.hashicorp.com/terraform/language/functions/abs)
 - [x] [ceil](https://developer.hashicorp.com/terraform/language/functions/ceil)
 - [x] [floor](https://developer.hashicorp.com/terraform/language/functions/floor)
 - [x] [log](https://developer.hashicorp.com/terraform/language/functions/log)
 - [x] [max](https://developer.hashicorp.com/terraform/language/functions/max)
 - [x] [min](https://developer.hashicorp.com/terraform/language/functions/min)
 - [x] [parseint](https://developer.hashicorp.com/terraform/language/functions/parseint)
 - [x] [pow](https://developer.hashicorp.com/terraform/language/functions/pow)
 - [x] [signum](https://developer.hashicorp.com/terraform/language/functions/signum)

### String functions:
 - [x] [chomp](https://developer.hashicorp.com/terraform/language/functions/chomp)
 - [x] [endswith](https://developer.hashicorp.com/terraform/language/functions/endswith)
 - [x] [format](https://developer.hashicorp.com/terraform/language/functions/format)
 - [ ] [formatlist](https://developer.hashicorp.com/terraform/language/functions/formatlist)
 - [x] [indent](https://developer.hashicorp.com/terraform/language/functions/indent)
 - [x] [join](https://developer.hashicorp.com/terraform/language/functions/join)
 - [x] [lower](https://developer.hashicorp.com/terraform/language/functions/lower)
 - [ ] [regex](https://developer.hashicorp.com/terraform/language/functions/regex)
 - [ ] [regexall](https://developer.hashicorp.com/terraform/language/functions/regexall)
 - [x] [replace](https://developer.hashicorp.com/terraform/language/functions/replace)
 - [x] [split](https://developer.hashicorp.com/terraform/language/functions/split)
 - [x] [startswith](https://developer.hashicorp.com/terraform/language/functions/startswith)
 - [x] [strrev](https://developer.hashicorp.com/terraform/language/functions/strrev)
 - [x] [substr](https://developer.hashicorp.com/terraform/language/functions/substr)
 - [x] [title](https://developer.hashicorp.com/terraform/language/functions/title)
 - [x] [trim](https://developer.hashicorp.com/terraform/language/functions/trim)
 - [x] [trimprefix](https://developer.hashicorp.com/terraform/language/functions/trimprefix)
 - [x] [trimsuffix](https://developer.hashicorp.com/terraform/language/functions/trimsuffix)
 - [x] [trimspace](https://developer.hashicorp.com/terraform/language/functions/trimspace)
 - [x] [upper](https://developer.hashicorp.com/terraform/language/functions/upper)

### Collection functions:
 - [x] [alltrue](https://developer.hashicorp.com/terraform/language/functions/alltrue)
 - [x] [anytrue](https://developer.hashicorp.com/terraform/language/functions/anytrue)
 - [x] [chunklist](https://developer.hashicorp.com/terraform/language/functions/chunklist)
 - [x] [coalesce](https://developer.hashicorp.com/terraform/language/functions/coalesce)
 - [x] [coalescelist](https://developer.hashicorp.com/terraform/language/functions/coalescelist)
 - [x] [compact](https://developer.hashicorp.com/terraform/language/functions/compact)
 - [x] [concat](https://developer.hashicorp.com/terraform/language/functions/concat)
 - [x] [contains](https://developer.hashicorp.com/terraform/language/functions/contains)
 - [x] [distinct](https://developer.hashicorp.com/terraform/language/functions/distinct)
 - [x] [element](https://developer.hashicorp.com/terraform/language/functions/element)
 - [x] [flatten](https://developer.hashicorp.com/terraform/language/functions/flatten)
 - [x] [index](https://developer.hashicorp.com/terraform/language/functions/index_function)
 - [x] [keys](https://developer.hashicorp.com/terraform/language/functions/keys)
 - [x] [length](https://developer.hashicorp.com/terraform/language/functions/length)
 - [x] [lookup](https://developer.hashicorp.com/terraform/language/functions/lookup)
 - [x] [matchkeys](https://developer.hashicorp.com/terraform/language/functions/matchkeys)
 - [x] [merge](https://developer.hashicorp.com/terraform/language/functions/merge)
 - [ ] [one](https://developer.hashicorp.com/terraform/language/functions/one)
 - [x] [range](https://developer.hashicorp.com/terraform/language/functions/range)
 - [x] [reverse](https://developer.hashicorp.com/terraform/language/functions/reverse)
 - [ ] [setintersection](https://developer.hashicorp.com/terraform/language/functions/setintersection)
 - [ ] [setproduct](https://developer.hashicorp.com/terraform/language/functions/setproduct)
 - [ ] [setsubtract](https://developer.hashicorp.com/terraform/language/functions/setsubtract)
 - [ ] [setunion](https://developer.hashicorp.com/terraform/language/functions/setunion)
 - [x] [slice](https://developer.hashicorp.com/terraform/language/functions/slice)
 - [x] [sort](https://developer.hashicorp.com/terraform/language/functions/sort)
 - [x] [sum](https://developer.hashicorp.com/terraform/language/functions/sum)
 - [x] [transpose](https://developer.hashicorp.com/terraform/language/functions/transpose)
 - [x] [values](https://developer.hashicorp.com/terraform/language/functions/values)
 - [x] [zipmap](https://developer.hashicorp.com/terraform/language/functions/zipmap)

### Encoding functions
- [x] [base64decode](https://developer.hashicorp.com/terraform/language/functions/base64decode)
- [x] [base64encode](https://developer.hashicorp.com/terraform/language/functions/base64encode)
- [x] [base64gzip](https://developer.hashicorp.com/terraform/language/functions/base64gzip)
- [x] [csvdecode](https://developer.hashicorp.com/terraform/language/functions/csvdecode)
- [x] [jsondecode](https://developer.hashicorp.com/terraform/language/functions/jsondecode)
- [x] [jsonencode](https://developer.hashicorp.com/terraform/language/functions/jsonencode)
- [ ] [textdecodebase64](https://developer.hashicorp.com/terraform/language/functions/textdecodebase64)
- [ ] [textencodebase64](https://developer.hashicorp.com/terraform/language/functions/textencodebase64)
- [x] [urlencode](https://developer.hashicorp.com/terraform/language/functions/urlencode)
- [ ] [yamldecode](https://developer.hashicorp.com/terraform/language/functions/yamldecode)
- [ ] [yamlencode](https://developer.hashicorp.com/terraform/language/functions/yamlencode)

### File system functions
- [x] [abspath](https://developer.hashicorp.com/terraform/language/functions/abspath)
- [x] [dirname](https://developer.hashicorp.com/terraform/language/functions/dirname)
- [x] [pathexpand](https://developer.hashicorp.com/terraform/language/functions/pathexpand)
- [x] [basename](https://developer.hashicorp.com/terraform/language/functions/basename)
- [x] [file](https://developer.hashicorp.com/terraform/language/functions/file)
- [x] [fileexists](https://developer.hashicorp.com/terraform/language/functions/fileexists)
- [ ] [fileset](https://developer.hashicorp.com/terraform/language/functions/fileset)
- [x] [filebase64](https://developer.hashicorp.com/terraform/language/functions/filebase64)
- [ ] [templatefile](https://developer.hashicorp.com/terraform/language/functions/templatefile)

### Date and Time functions
- [ ] [formatdate](https://developer.hashicorp.com/terraform/language/functions/formatdate)
- [x] [timeadd](https://developer.hashicorp.com/terraform/language/functions/timeadd)
- [x] [timecmp](https://developer.hashicorp.com/terraform/language/functions/timecmp)
- [x] [timestamp](https://developer.hashicorp.com/terraform/language/functions/timestamp)

### Hash and Crypto functions
- [x] [base64sha256](https://developer.hashicorp.com/terraform/language/functions/base64sha256)
- [x] [base64sha512](https://developer.hashicorp.com/terraform/language/functions/base64sha512)
- [x] [bcrypt](https://developer.hashicorp.com/terraform/language/functions/bcrypt)
- [x] [filebase64sha256](https://developer.hashicorp.com/terraform/language/functions/filebase64sha256)
- [x] [filebase64sha512](https://developer.hashicorp.com/terraform/language/functions/filebase64sha512)
- [x] [filemd5](https://developer.hashicorp.com/terraform/language/functions/filemd5)
- [x] [filesha1](https://developer.hashicorp.com/terraform/language/functions/filesha1)
- [x] [filesha256](https://developer.hashicorp.com/terraform/language/functions/filesha256)
- [x] [filesha512](https://developer.hashicorp.com/terraform/language/functions/filesha512)
- [x] [md5](https://developer.hashicorp.com/terraform/language/functions/md5)
- [x] [rsadecrypt](https://developer.hashicorp.com/terraform/language/functions/rsadecrypt)
- [x] [sha1](https://developer.hashicorp.com/terraform/language/functions/sha1)
- [x] [sha256](https://developer.hashicorp.com/terraform/language/functions/sha256)
- [x] [sha512](https://developer.hashicorp.com/terraform/language/functions/sha512)
- [x] [uuid](https://developer.hashicorp.com/terraform/language/functions/uuid)
- [ ] [uuidv5](https://developer.hashicorp.com/terraform/language/functions/uuidv5)

### IP network functions
- [x] [cidrhost](https://developer.hashicorp.com/terraform/language/functions/cidrhost)
- [x] [cidrnetmask](https://developer.hashicorp.com/terraform/language/functions/cidrnetmask)
- [x] [cidrsubnet](https://developer.hashicorp.com/terraform/language/functions/cidrsubnet)
- [ ] [cidrsubnets](https://developer.hashicorp.com/terraform/language/functions/cidrsubnets)

### Type conversion functions
 - [ ] [can](https://developer.hashicorp.com/terraform/language/functions/can)
 - [ ] [nonsensitive](https://developer.hashicorp.com/terraform/language/functions/nonsensitive)
 - [ ] [sensitive](https://developer.hashicorp.com/terraform/language/functions/sensitive)
 - [x] [tobool](https://developer.hashicorp.com/terraform/language/functions/tobool)
 - [x] [tolist](https://developer.hashicorp.com/terraform/language/functions/tolist)
 - [ ] [tomap](https://developer.hashicorp.com/terraform/language/functions/tomap)
 - [x] [tonumber](https://developer.hashicorp.com/terraform/language/functions/tonumber)
 - [x] [toset](https://developer.hashicorp.com/terraform/language/functions/toset)
 - [x] [tostring](https://developer.hashicorp.com/terraform/language/functions/tostring)
 - [ ] [try](https://developer.hashicorp.com/terraform/language/functions/try)
 - [ ] [type](https://developer.hashicorp.com/terraform/language/functions/type)

**Comment by mikhailshilkov** [comment]
I feel like we got where we wanted to be here (or maybe even further), so I don't expect further investments in more functions in short term. To make this explicit, I'll close the issue as done.

**Comment by Zaid-Ajaj** [comment]
@mikhailshilkov sounds good. We can add more functions as we go.
